#+TITLE: Intro
#+AUTHOR: Nicky

#+OPTIONS: toc:nil author:nil date:nil title:t

#+LATEX_CLASS: subfiles
#+LATEX_CLASS_OPTIONS: [sicm_sagemath]

** Introduction

This is a translation to Python and Sagemath of (most of) the Scheme code of the book `Structure and interpretation of classical mechanics' by Sussman and Wisdom.
When referring to /the book/, I mean their book.
I expect the reader to read the related parts of the book, and use the Scheme code of the book to understand the Python code below.
In other words, I don't explain much of the logic of the code in this document.
I'll try to stick to the naming of functions and variables as used in the book.
I also try to keep the functional programming approach of the book; consequently, I don't strive to the most pythonic code possible.
To keep the code clean, I never protect functions against stupid input; realize that this is research project, the aim is not to produce a fool-proof software product.


I tend to place explanations, comments, and observations about the code and the results /above/ the code blocks.

I wrote this document in emacs and org mode.
When developing, I first made a sage file with all code for a specific section of the book.
Once all worked, I copied the code to an org file and make code blocks.
Once done, I tangled to code of the org mode to a utils.sage file containing general functions and code that is useful for other sections, and section specific code to a section.sage file.

I also found it convenient to test things in a ~tests.sage~ file. Then, by opening a sage session in the command prompt and attaching the session to the file (~attach("tests.sage")~), I could edit within emacs and see the consequences directly in the sage session.


- An online version of the book: [[https://tgvaughan.github.io/sicm/]]
- An org file of the book  with Scheme: https://github.com/mentat-collective/sicm-book/blob/main/org/chapter001.org
- [[https://doc.sagemath.org/html/en/reference/]]
- Handy tuples: https://github.com/jtauber/functional-differential-geometry
- A port to Clojure: https://github.com/sicmutils/sicmutils
- ChatGPT proved to be a great help in the process of becoming familiar with Scheme and Sagemath.
